// Feature-local tokens. No global theme, ribbon, or app typography changes.
export const schedulingType = {
  base: { fontSize: 12.5, fontWeight: 400, lineHeight: 1.32 },
  control: { fontSize: 12.5, fontWeight: 400, lineHeight: 1.25 },
  meta: { fontSize: 10.5, fontWeight: 400, lineHeight: 1.3 },
  status: { fontSize: 10.5, fontWeight: 700, lineHeight: 1.2 },
  fieldLabel: { fontSize: 11.5, fontWeight: 600, lineHeight: 1.2 },
  eyebrow: { fontSize: 11, fontWeight: 700, letterSpacing: ".025em", lineHeight: 1.2 },
  panelTitle: { fontSize: 12.5, fontWeight: 700 },
  cardTitle: { fontSize: 12, fontWeight: 700, lineHeight: 1.25 },
  pageTitle: { fontSize: 18, fontWeight: 700, lineHeight: 1.2 },
  drawerTitle: { fontSize: 17, fontWeight: 700, lineHeight: 1.2 },
  weekday: { fontSize: 11.5, fontWeight: 700 },
  date: { fontSize: 10.5, fontWeight: 400 },
  amPm: { fontSize: 10, fontWeight: 700 },
  period: { fontSize: 10.5, fontWeight: 700 },
  button: { fontSize: 12, fontWeight: 600 },
};

export const schedulingTypographySx = {
  fontFamily: '"Segoe UI", Arial, sans-serif',
  ...schedulingType.base,
  "& .MuiTypography-root, & .MuiInputBase-root, & .MuiButton-root, & .MuiMenuItem-root": { fontFamily: '"Segoe UI", Arial, sans-serif' },
  "& .MuiTypography-body1, & .MuiTypography-body2, & .MuiAlert-root": schedulingType.base,
  "& .MuiTypography-caption, & .MuiChip-label": schedulingType.meta,
  "& .MuiTypography-subtitle1, & .MuiTypography-subtitle2": schedulingType.panelTitle,
  "& .MuiTypography-h4, & .MuiTypography-h5, & .MuiTypography-h6": schedulingType.pageTitle,
  "& .MuiInputBase-root, & .MuiMenuItem-root": schedulingType.control,
  "& .MuiOutlinedInput-root": { borderRadius: "3px" },
  "& .MuiOutlinedInput-root:not(.MuiInputBase-multiline)": { height: 34 },
  "& .MuiOutlinedInput-input": { px: "10px", py: "7px" },
  "& .MuiButton-root": { ...schedulingType.button, minHeight: 32, py: 0, px: "10px", borderRadius: "3px" },
  "& .MuiButton-sizeSmall": { minHeight: 28 },
  "& .MuiTypography-root[component='label'], & label.MuiTypography-root": schedulingType.fieldLabel,
};
